version: '3.4'

networks:
  altinnplatform_network:
    external: false

services:
  altinn_app_texts:
    container_name: altinn-app-texts
    image: altinnapptexts:latest
    restart: always
    networks:
      - altinnplatform_network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5090
    ports:
      - "5090:5090"
    build:
      context: .
      dockerfile: Dockerfile



